// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrdersManagement.Data;

#nullable disable

namespace OrdersManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518045755_ModelosDb")]
    partial class ModelosDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OrdersManagement.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("OrdersManagement.Models.Diagnostico", b =>
                {
                    b.Property<int>("DiagnosticoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DiagnosticoId"));

                    b.Property<decimal>("CostoRef")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("CostoRep")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("DiagnosticoFalla")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrdenServicioId")
                        .HasColumnType("int");

                    b.HasKey("DiagnosticoId");

                    b.HasIndex("OrdenServicioId");

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("OrdersManagement.Models.Equipo", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EquipoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoEquipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EquipoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("OrdersManagement.Models.Evidencia", b =>
                {
                    b.Property<int>("EvidenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EvidenciaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrdenServicioId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Registro")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EvidenciaId");

                    b.HasIndex("OrdenServicioId");

                    b.ToTable("Evidencias");
                });

            modelBuilder.Entity("OrdersManagement.Models.OrdenServicio", b =>
                {
                    b.Property<int>("OrdenServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrdenServicioId"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Falla")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Presupuesto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("int");

                    b.HasKey("OrdenServicioId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("OrdenesServicio");
                });

            modelBuilder.Entity("OrdersManagement.Models.Tecnico", b =>
                {
                    b.Property<int>("TecnicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TecnicoId"));

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("TecnicoId");

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("OrdersManagement.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("int");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UsuarioId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("OrdersManagement.Models.Diagnostico", b =>
                {
                    b.HasOne("OrdersManagement.Models.OrdenServicio", "OrdenServicio")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("OrdenServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("OrdersManagement.Models.Equipo", b =>
                {
                    b.HasOne("OrdersManagement.Models.Cliente", "Cliente")
                        .WithMany("Equipos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("OrdersManagement.Models.Evidencia", b =>
                {
                    b.HasOne("OrdersManagement.Models.OrdenServicio", "OrdenServicio")
                        .WithMany("Evidencias")
                        .HasForeignKey("OrdenServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("OrdersManagement.Models.OrdenServicio", b =>
                {
                    b.HasOne("OrdersManagement.Models.Equipo", "Equipo")
                        .WithMany("OrdenesServicio")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrdersManagement.Models.Tecnico", "Tecnico")
                        .WithMany("OrdenesServicio")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("OrdersManagement.Models.Usuario", b =>
                {
                    b.HasOne("OrdersManagement.Models.Tecnico", "Tecnico")
                        .WithMany("Usuarios")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("OrdersManagement.Models.Cliente", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("OrdersManagement.Models.Equipo", b =>
                {
                    b.Navigation("OrdenesServicio");
                });

            modelBuilder.Entity("OrdersManagement.Models.OrdenServicio", b =>
                {
                    b.Navigation("Diagnosticos");

                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("OrdersManagement.Models.Tecnico", b =>
                {
                    b.Navigation("OrdenesServicio");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
